
install:
  - set QTDIR=C:\Qt\5.11.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake porymap.pro -config release
  - mingw32-make -j2
  - windeployqt release/porymap.exe

artifacts:
  - path: release/*.exe
    name: porymap-win32

deploy:
  description: 'Built by AppVeyor'
  provider: GitHub
  repository: garakmon/porymap
  skip_cleanup: true
  auth_token:
    secure: MLSwoIXXuZaI9iKbxUSX7ErtiRW8Q9MSuPOqS8EYJj68f4sx8eERXWBLX7MpmmEb
  artifacts: porymap-win32
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
